// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace campusCentralApi.Models
{
    public partial class ClassGroup
    {
        [Key]
        public int ClassGroupId { get; set; }
        public int? CourseId { get; set; }
        public int? ClassGroupEnrolledUsersQuantity { get; set; }
        public TimeSpan? StartAt { get; set; }
        public int? Status { get; set; }
        public int? MinEnrolledUsers { get; set; }
        public int? MaxEnrolledUsers { get; set; }
    }
}