// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace campusCentralApi.Models
{
    public partial class UniversitySystemContext : DbContext
    {
        public UniversitySystemContext()
        {
        }

        public UniversitySystemContext(DbContextOptions<UniversitySystemContext> options)
            : base(options)
        {
        }
        public virtual DbSet<UserAccount> UserAccount { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}