// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace campusCentralApi.Models
{
    public partial class TopicScheduleTime
    {
        [Key]
        public int TopicScheduleTimeId { get; set; }
        public int TopicId { get; set; }
        public int CourseId { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string PeriodTypeScheduled { get; set; }
    }
}